### ISSUE TITLE
Decimal place - example function outputs vs. the instruction

### ISSUE THREAD

**Issue by JStrebeyko** [daftcode/rorlevelup2019#16]
Hi,
The text says that the output should be rounded to the second decimal place:
>  Kwota zwracana przez obiekt `Converter` powinna być zaokrąglona do dwóch miejsc po przecinku.

...Yet the function outputs presented are rounded towards the first:

`converter.convert_to(:usd) # => 11.3`

Cheers :beers:

**Comment by ahawrylak** [comment]
Thanks for opening issue!
`Converter` should return number rounded to two decimal places, not print string with it to STDOUT. If we have value like `11.3` and try to round it, we're going to get `11.3` back, which is fine. Notice that:
```ruby
(11.3).round(2) # => 11.3
(11.3777).round(2) # => 11.38
```

**Comment by JStrebeyko** [comment]
Thanks for the response! Just realized the given scenario does not produce fractions :man_facepalming:
I am grateful for this string print-out bit especially; adjusting the PR accordingly :pencil2:
